---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
  tags:
    - clickhouse

- name: Vector installation
  hosts: vector
  roles:
    - vector-role
  tags:
    - vector

- name: Install lighthouse
  hosts: lighthouse
  pre_tasks:
    - name: Instal epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
    - name: Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
      notify: start-nginx
    - name: Install git
      become: true
      ansible.builtin.yum:
        name: git
  roles:
    - lighthouse-role
  tags:
    - lighthouse
...
