---
- name: Download lighthouse
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/VKCOM/lighthouse.git'
    dest: /var/www/lighthouse
    update: no
- name: Fix owner and mode
  become: true
  ansible.builtin.file:
    path: /var/www/lighthouse
    state: directory
    mode: '0755'
    owner: ivan
- name: nginx config
  become: true
  ansible.builtin.template:
    src: lighthouse-role/templates/lighthouse.j2
    dest: /etc/nginx/nginx.conf
    owner: ivan
  notify: start-nginx